### ISSUE TITLE
Improvement suggestion for deletion interface

### ISSUE THREAD

**Issue by SuperCuber** [DrBenana/SimpleSQL#1]
You can use almost the same syntax as updating:
```python
del table["column1", "WHERE column2='something'"]
```

BTW I'm EntityBlank from FXP, I think we were in a Skype group together for a while :)

**Comment by BenTimor** [comment]
Hey! Thank you for the suggestion.
I really want to do it but I'm not sure how it works.

And yeah, we were on Omer's group. Aren't you in the current Whatsapp group? 🤔

**Comment by SuperCuber** [comment]
> I really want to do it ut I'm not sure how it works.

Check out the `__delitem__` magic method

> Aren't you in the current Whatsapp group?

Nope, I'll send you my phone number to your email :)

**Comment by BenTimor** [comment]
Added and pushed into GitHub.
PyPi packaged is also updated.

Thank you very much! ;)
